# Generated by Django 5.0 on 2023-12-22 11:26

import oguztube.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oguztube', '0002_shorts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='video',
            field=models.FileField(upload_to='videos', verbose_name='Wideo'),
        ),
    ]
