# Generated by Django 5.0 on 2023-12-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oguztube', '0003_alter_shorts_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='shorts',
            name='video',
            field=models.FileField(upload_to='videos', verbose_name='Wideo (1x2 size required)'),
        ),
    ]
