# Generated by Django 5.0 on 2023-12-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oguztube', '0008_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='oguztube.categories'),
        ),
    ]
